---
version: "3.8"
services:
  movies:
    image: akhila06112000/train:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: akhila06112000/paytm:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
